use Covid;
select * from CovidDeaths;
select * from CovidDeaths1;

select iso_code,continent,location,date,total_tests,population from CovidDeaths;

with t1 as(select location,continent, COALESCE (REPLACE(TOTAL_TESTS,'NA','NULL'),'0') as total_tests,date,population from CovidDeaths)
,t2 as (select *,MONTH(date)month1 from t1)
select LOCATION,SUM(CAST(total_tests AS bigint)) from t2 GROUP BY LOCATION ORDER BY 1,2;

SELECT CONTINENT,DATE,TOTAL_CASES,POPULATION,TOTAL_DEATHS,NEW_CASES FROM CovidDeaths1;
SELECT CONTINENT,(TOTAL_CASES/POPULATION)*100 FROM CovidDeaths1;

--FIND TOTAL CASES TO TOTAL DEATHS RATIO
SELECT LOCATION,TOTAL_CASES,TOTAL_DEATHS,(((TOTAL_DEATHS/TOTAL_CASES)*100)) AS RATIO 
FROM CovidDeaths1 WHERE LOCATION LIKE '%STATES%';

--FIND THE PERCANTAGE TOTAL CASES TO POPLULATION I.E CHANCES OF GETTING INFECTED
SELECT LOCATION,TOTAL_CASES,POPULATION,ROUND((total_cases/POPULATION)*100,2) AS RATIO 
FROM CovidDeaths1 ORDER BY 1,2;

--FIND WHICH COUNTRY HAS HIGHEST INFECTION RATIO COMPARED TO POPULATION
SELECT LOCATION,MAX(TOTAL_CASES)AS HIGHESTCASES,POPULATION,ROUND(MAX(total_cases/POPULATION)*100,2) 
AS RATIO 
FROM CovidDeaths1 WHERE LOCATION LIKE 'INDIA'
GROUP BY LOCATION,POPULATION 
ORDER BY RATIO DESC;

SELECT LOCATION,CONTINENT,MAX(CAST(TOTAL_DEATHS AS INT))AS DEATHS FROM CovidDeaths1
WHERE continent IS NOT NULL
GROUP BY LOCATION,CONTINENT ORDER BY DEATHS DESC;

SELECT CONTINENT,MAX(CAST(TOTAL_DEATHS AS INT))AS DEATHS FROM CovidDeaths1
WHERE continent IS NOT NULL
GROUP BY CONTINENT ORDER BY DEATHS DESC;

--SHOWING CONTINENTS WITH HIGHEST DEATH COUNT TO POPULATION
SELECT CONTINENT,COUNT(CAST(TOTAL_DEATHS AS INT)) FROM CovidDeaths1
WHERE CONTINENT IS NOT NULL
 GROUP BY CONTINENT;
 

with t1 as(select team,noc,case when medal='NA' then '0' else medal  end  as medals from athlete_events$)
,t2 as (select a.* from t1 as a join noc_regions$ as noc1 on a.noc=noc1.noc)
,t3 as (select team,medals  from t2 )
select * from t3 as data pivot( count(medals) for medals in([Gold],[Silver],[Bronze]))as pivottable order by Gold desc;

SELECT DATE FROM CovidDeaths1;
WITH T AS (SELECT CONTINENT,(TOTAL_DEATHS )AS TOTAL_DEATHS,CASE 
WHEN MONTH(DATE) =1 THEN 'JANUARY' 
WHEN MONTH(DATE)=2 THEN 'FEBUARY' 
WHEN MONTH(DATE)=3 THEN 'MARCH'
WHEN MONTH(DATE)=4 THEN 'APRIL'
WHEN MONTH(DATE)=5 THEN 'MAY'
WHEN MONTH(DATE)=6 THEN 'JUNE'
WHEN MONTH(DATE)=7 THEN 'JULY'
WHEN MONTH(DATE)= 8 THEN 'AUGUST'
WHEN MONTH(DATE)=9 THEN 'SEPTEMBER'
WHEN MONTH(DATE)=10 THEN 'OCTOBER'
WHEN MONTH(DATE)=11 THEN 'NOVEMBER'
WHEN MONTH(DATE)=12 THEN 'DECEMBER'
END  AS MONTHS FROM CovidDeaths1 WHERE continent IS NOT NULL),
T2 AS(
SELECT * FROM T AS CD  PIVOT(MAX(TOTAL_DEATHS)  FOR MONTHS IN
([January], [February], [March], [April], [May], [June], [July], [August], [September], [October],[ November],[December]))AS PIVOTTABLE),
T3 AS(SELECT CONTINENT,COALESCE (REPLACE([January],'NULL','0'),'0') AS JAN, COALESCE (REPLACE([MARCH],'NULL','0'),'0') AS MAR,COALESCE([FEBRUARY],0) AS FEB,
COALESCE([APRIL],0) AS APR,
COALESCE([MAY],0) AS MAY,
COALESCE([JUNE],0) AS JUN,
COALESCE([JULY],0) AS JUL,
COALESCE([AUGUST],0) AS AUG,
COALESCE([SEPTEMBER],0) AS SEP,
COALESCE([OCTOBER],0)AS OCT,
COALESCE([DECEMBER],0)AS DEC
FROM T2)
SELECT *,CAST(JAN+FEB+MAR+APR+MAY+JUN+JUL+AUG+SEP+OCT+DEC AS INT) FROM T3
;

SELECT MAX(CAST(TOTAL_DEATHS AS INT)),CONTINENT  FROM CovidDeaths1 WHERE continent IS NOT NULL GROUP BY continent;
SELECT CONTINENT,total_deaths FROM CovidDeaths1;
SELECT continent,MONTH(DATE) AS MONTH,TOTAL_DEATHS AS MAX FROM CovidDeaths1 WHERE CONTINENT IS NOT NULL AND LOCATION LIKE '%INDIA' GROUP BY MONTH(DATE) ,CONTINENT ORDER BY MONTH;